### ISSUE TITLE
Publish to Open-VSX

### ISSUE THREAD

**Issue by Orochimarufan** [guyskk/language-cython-for-vscode#12]
Due to VS Marketplace ToU, thrid-party builds of VSCode or derivatives aren't allowed to connect to it. Instead, most have converged on an open alternative at https://open-vsx.org

If it's not too much trouble, it would be nice if you could publish to Open-VSX as well as the VS Marketplace. See https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension for info and https://github.com/HaaLeo/publish-vscode-extension for possible automation opportunities

**Comment by guyskk** [comment]
Done. https://open-vsx.org/extension/guyskk/language-cython
