### ISSUE TITLE
Highlighting in jupyter

### ISSUE THREAD

**Issue by btvd** [guyskk/language-cython-for-vscode#13]
Hey! I've tried to use ext for working with jupyter notebook, but failed to see any changes in highlighting. May be I did something wrong with activating ext? I've just installed it from marketplace. Could not build it because I do not have vsce on Win10. Can you give me any recommendations what to do?

**Comment by guyskk** [comment]
1. How do you use jupyter notebook? maybe share some screenshots?
2. The cython extension only works on cython source code file (eg: .pyx https://github.com/guyskk/language-cython-for-vscode/blob/master/package.json#L25), I didn't use it with notebook ever.
3. You can follow links in https://github.com/guyskk/language-cython-for-vscode#development to install tools and build the extension.

**Comment by btvd** [comment]
> 1. How do you use jupyter notebook? maybe share some screenshots?
> 2. The cython extension only works on cython source code file (eg: .pyx https://github.com/guyskk/language-cython-for-vscode/blob/master/package.json#L25), I didn't use it with notebook ever.
> 3. You can follow links in https://github.com/guyskk/language-cython-for-vscode#development to install tools and build the extension.

Thank you for reply! I'm on Win10, and I do not have vsce in my cmd. Do you have guide how to build it on Win10? Coz when I do: _vsce --version_
I get:  _'vsce' is not recognized as an internal or external command, operable program or batch file._

**Comment by guyskk** [comment]
From doc https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce , the vsce is a npm package, maybe you should check your nodejs and npm installation, if your nodejs and npm works well then vsce should works too.

**Comment by btvd** [comment]
> From doc https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce , the vsce is a npm package, maybe you should check your nodejs and npm installation, if your nodejs and npm works well then vsce should works too.

Thank you for help! I could build and install the extension.
